import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import tailwindcss from "@tailwindcss/vite";
import { readdir } from "node:fs/promises";
import react from "@astrojs/react";

type AutogeneratedEntry = (
  | string
  | {
      label: string;
      translations?: Record<string, string> | undefined;
      items: any;
      collapsed: boolean;
    }
)[];

async function nestedAutogenerated(
  path: string,
  translations: Record<string, Record<string, string>>,
  priorize?: string[] | undefined,
): Promise<AutogeneratedEntry> {
  const full_path = "./src/content/docs/" + path;
  const dir = await readdir(full_path);
  let pages: AutogeneratedEntry = [];
  let folders: AutogeneratedEntry = [];
  for await (const item of dir) {
    if (item.endsWith(".md")) {
      pages.push(path + "/" + item.replace(".md", ""));
      continue;
    }
    if (item.endsWith(".mdx")) {
      pages.push(path + "/" + item.replace(".mdx", ""));
      continue;
    }
    if (translations && Object.hasOwn(translations, item)) {
      folders.push({
        label: translations[item].en,
        translations: translations[item],
        items: await nestedAutogenerated(
          path + "/" + item,
          translations,
          priorize,
        ),
        collapsed: true,
      });
      continue;
    }
    folders.push({
      label: item,
      items: await nestedAutogenerated(
        path + "/" + item,
        translations,
        priorize,
      ),
      collapsed: true,
    });
  }
  if (priorize) {
    pages.sort((a, b) => {
      return (
        priorize.findIndex((str) => b == str) +
        1 -
        (priorize.findIndex((str) => a == str) + 1)
      );
    });
  }
  return pages.concat(folders);
}

// https://astro.build/config
export default defineConfig({
  site: "https://steelmc.dev/",
  base: "/",
  output: "static",

  integrations: [
    starlight({
      customCss: ["./src/styles/global.css"],
      favicon: "/favicon.png",
      title: {
        en: "Steel-Docs",
        de: "Steel-Doku",
        es: "Documentación de Steel",
      },
      logo: {
        src: "./public/steel_logo.png",
        alt: "",
      },

      social: [
        {
          icon: "discord",
          label: "Discord",
          href: "/discord",
        },
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/Steel-Foundation/SteelMC",
        },
      ],
      sidebar: [
        {
          label: "Getting started",
          translations: {
            es: "Primeros pasos",
            de: "Erste Schritte",
          },
          items: [{autogenerate: { directory: "getting-started" }}],
        },
        {
          label: "Configuration",
          translations: {
            es: "Configuración",
            de: "Konfiguration",
          },
          items: [{autogenerate: { directory: "configuration" }}],
        },
        {
          label: "Commands",
          items: [{autogenerate: { directory: "commands" }}],
        },
        {
          label: "Development",
          translations: {
            es: "Desarrollo",
            de: "Entwicklung",
          },
          items: await nestedAutogenerated(
            "development",
            {
              blocks: {
                en: "Blocks",
                es: "Bloques",
                de: "Blöcke",
              },
              items: {
                en: "Items",
                es: "Objetos",
                de: "Items",
              },
              commands: {
                en: "Commands",
                es: "Comandos",
                de: "Befehle",
              },
              network: {
                en: "Network",
                es: "Red",
                de: "Netzwerk",
              },
              tools: {
                en: "Tools",
                es: "Herramientas",
                de: "Werkzeuge",
              },
            },
            [
              "development/start-contributing",
              "development/network/network",
              "development/tools/steel_extractor",
            ],
          ),
        },
        {
          label: "Reference",
          translations: {
            es: "Referencias",
            de: "Referenz",
          },
          items: [{autogenerate: { directory: "reference" }}],
        },
      ],
      editLink: {
        baseUrl: "https://github.com/Steel-Foundation/SteelDocs/edit/main/",
      },
      lastUpdated: true,
      defaultLocale: "root",
      locales: {
        // English docs in `src/content/docs/`
        root: {
          label: "English",
          lang: "en",
        },
        de: {
          label: "Deutsch",
          lang: "de",
        },
        es: {
          label: "Español",
          lang: "es",
        },
      },
    }),
    react(),
  ],

  vite: {
    plugins: [tailwindcss()],
  },
});
